version: '3'

networks:
  frontend:
    external: true

services:
  app:
    image: portainer/portainer-ce:latest
    container_name: portainer-app
    restart: always
    volumes:
      - /your/path/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend